name: PR Review and Security Checks
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  security-checks:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      # Copilot PR Overview
      - name: GitHub Copilot PR Overview
        uses: github/copilot-preview@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          operation: 'pull-request-summary'
      
      # Copilot Security Analysis
      - name: GitHub Copilot Security Analysis
        uses: github/copilot-preview@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      # CodeQL Analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        
      # Dependency Review
      - name: Dependency Review
        uses: actions/dependency-review-action@v3

  check-protected-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for protected file changes
        id: check_files
        run: |
          PROTECTED_FILES=$(git diff --name-only origin/main... | grep -E "src/context/AuthContext.jsx|.github/")
          if [ ! -z "$PROTECTED_FILES" ]; then
            echo "Protected files modified:"
            echo "$PROTECTED_FILES"
            echo "::set-output name=protected_files_changed::true"
          fi
      
      - name: Comment on PR
        if: steps.check_files.outputs.protected_files_changed == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: '⚠️ This PR modifies protected files that require approval from @kdogdevs'
            })
