name: PR Review and Security Checks
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  security-checks:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      # Copilot PR Review
      - name: Request Copilot PR Review
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.name,
              pull_number: context.issue.number,
              event: 'COMMENT',
              body: '👋 Requesting Copilot review for this PR'
            });
          
      # CodeQL Analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        
      # Dependency Review
      - name: Dependency Review
        uses: actions/dependency-review-action@v3

  check-protected-files:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check for protected file changes
        id: check_files
        run: |
          git fetch origin main
          PROTECTED_FILES=$(git diff --name-only origin/main...HEAD | grep -E "src/context/AuthContext.jsx|.github/" || true)
          if [ ! -z "$PROTECTED_FILES" ]; then
            echo "Protected files modified:"
            echo "$PROTECTED_FILES"
            echo "protected_files_changed=true" >> $GITHUB_OUTPUT
          else
            echo "No protected files modified."
            echo "protected_files_changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Comment on PR
        if: steps.check_files.outputs.protected_files_changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: '⚠️ This PR modifies protected files that require approval from @kdogdevs\n\nModified files:\n```\n' + 
                process.env.PROTECTED_FILES + '\n```'
            })
        env:
          PROTECTED_FILES: ${{ steps.check_files.outputs.protected_files }}
